LABEL_TRANSLATIONS = {
    "afternoon": "دوپہر",
    "allow": "اجازت دیں",
    "aoa dear brothers and sisters": "السلام علیکم پیارے بھائیو اور بہنو",
    "are you busy today": "کیا آپ آج مصروف ہیں",
    "best": "بہترین",
    "can we discuss this later": "کیا ہم یہ بعد میں بات کر سکتے ہیں",
    "can you help me": "کیا آپ میری مدد کر سکتے ہیں",
    "can you repeat that": "کیا آپ دوبارہ کہہ سکتے ہیں",
    "clean": "صاف",
    "day": "دن",
    "do you understand": "کیا آپ سمجھتے ہیں",
    "eat": "کھانا",
    "evening": "شام",
    "fail": "ناکام",
    "faislabad": "فیصل آباد",
    "fine": "ٹھیک",
    "free": "خالی",
    "friend": "دوست",
    "good afternoon": "نیک دوپہر",
    "good bye": "خدا حافظ",
    "good day": "نیک دن",
    "good evening": "نیک شام",
    "good morning": "صبح بخیر",
    "good night": "شب بخیر",
    "happy anniversay": "سالگرہ مبارک",
    "happy birthday": "یوم پیدائش مبارک",
    "happy to meet you": "آپ سے مل کر خوشی ہوئی",
    "happy to meet you too": "مجھے بھی آپ سے مل کر خوشی ہوئی",
    "hey guys hope you are doing great": "ہیلو دوستو امید ہے آپ سب ٹھیک ہیں",
    "hi": "ہائے",
    "hi there": "ہائے",
    "home": "گھر",
    "how are you": "آپ کیسے ہیں",
    "how are you  i am good alhamdulilah": "آپ کیسے ہیں، میں ٹھیک ہوں الحمدللہ",
    "how did your meeting go": "آپ کی میٹنگ کیسی رہی",
    "i agree with your idea": "میں آپ کے خیال سے متفق ہوں",
    "i am feeling stressed today": "میں آج پریشان محسوس کر رہا ہوں",
    "i am fine": "میں ٹھیک ہوں",
    "i am going to school or work": "میں اسکول یا کام پر جا رہا ہوں",
    "i am hungry": "مجھے بھوک لگی ہے",
    "i dont understand": "مجھے سمجھ نہیں آیا",
    "i have a different opinion": "میری مختلف رائے ہے",
    "i need more time think": "مجھے سوچنے کے لیے مزید وقت چاہیے",
    "islamabad": "اسلام آباد",
    "karachi": "کراچی",
    "lahore": "لاہور",
    "lets eat together": "آئیں ساتھ کھانا کھائیں",
    "lets start now": "آئیں ابھی شروع کریں",
    "meet": "ملنا",
    "morning": "صبح",
    "multan": "ملتان",
    "my name is": "میرا نام ہے",
    "name": "نام",
    "night": "رات",
    "peshawar": "پشاور",
    "please": "براہ کرم",
    "rawalpindi": "راولپنڈی",
    "salam": "سلام",
    "sleep": "سونا",
    "sorry": "معذرت",
    "sun": "سورج",
    "thank you": "شکریہ",
    "wait": "انتظار کریں",
    "wakeup": "جاگو",
    "water": "پانی",
    "wedding or marriage": "شادی",
    "welcome": "خوش آمدید",
    "welcome here": "یہاں خوش آمدید",
    "what are your plans for tomorrow": "کل کے لیے آپ کا کیا پلان ہے",
    "what is your name": "آپ کا نام کیا ہے",
    "what time is it": "ابھی کیا وقت ہے",
    "where are you going": "آپ کہاں جا رہے ہیں",
    "wsalam": "وعلیکم سلام",
}

def translate(label, target_lang="en"):
    if target_lang == "ur":
        return LABEL_TRANSLATIONS.get(label.lower(), label)
    return label