import React, {useEffect, useMemo, useRef, useState} from 'react';
import {
  Animated,
  Dimensions,
  Image,
  PermissionsAndroid,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import * as RNAnimatable from 'react-native-animatable';
import FontAwesome5 from 'react-native-vector-icons/FontAwesome5';
import {WebView} from 'react-native-webview';
import {useSelector} from 'react-redux';
import Voice from '@react-native-voice/voice';

import AvatarImg from '../avatar.jpeg';
// psl_animation_library.json is generated by backend/extract_holistic_animation.py
// Falls back to the old psl_library.json if new library not available
let pslLibrary = {};
try {
  pslLibrary = require('../psl_animation_library.json');
} catch {
  try {
    pslLibrary = require('../psl_library.json');
  } catch {
    pslLibrary = {};
  }
}

const {width} = Dimensions.get('window');
const AVATAR_SIZE = width - 40;
const ANDROID_ASSET_URI = 'file:///android_asset/avatar_model.glb';
const METRO_FALLBACK_URI =
  'http://10.0.2.2:8081/assets/assets/models/avatar_model.glb';

// ─── WebGL / Three.js Viewer ──────────────────────────────────────────────────

const createViewerHtml = modelUris => `
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <style>
    html, body { margin: 0; width: 100%; height: 100%; overflow: hidden; background: transparent; }
    canvas { width: 100vw; height: 100vh; display: block; }
    #status { position: absolute; top: 50%; left: 50%; transform: translate(-50%,-50%);
      color: rgba(255,255,255,0.5); font-family: sans-serif; font-size: 14px; pointer-events: none; }
  </style>
</head>
<body>
  <div id="status">Loading avatar…</div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/mrdoob/three.js@r128/examples/js/loaders/GLTFLoader.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/mrdoob/three.js@r128/examples/js/controls/OrbitControls.js"></script>
  <script>
    // ── Scene globals ──────────────────────────────────────────────────────────
    let scene, camera, renderer, controls, mixer, clock, avatarRoot, idleAction;
    const MODEL_URLS = ${JSON.stringify(modelUris)};
    window.bones = {};

    // ── Animation state ────────────────────────────────────────────────────────
    let animFrames = [];
    let animIndex  = 0;
    let animTimer  = null;
    let animFPS    = 15;
    let restQuats  = {};
    let restBoneDirs = {};
    let restWorldDirs = {};
    let idleTimer  = null;
    let returnIdleTimeout = null;
    let gestureActive = false;
    let fixedAvatarPosition = new THREE.Vector3();
    let fixedAvatarScale = 1;
    const JOINT_SCALE = 2.2;
    const ARM_BONES = ['rightArm', 'rightForeArm', 'leftArm', 'leftForeArm'];
    const FINGER_BONE_KEYS = [
      'rightHand','leftHand',
      'rightHandThumb1','rightHandThumb2','rightHandThumb3',
      'rightHandIndex1','rightHandIndex2','rightHandIndex3',
      'rightHandMiddle1','rightHandMiddle2','rightHandMiddle3',
      'rightHandRing1','rightHandRing2','rightHandRing3',
      'rightHandPinky1','rightHandPinky2','rightHandPinky3',
      'leftHandThumb1','leftHandThumb2','leftHandThumb3',
      'leftHandIndex1','leftHandIndex2','leftHandIndex3',
      'leftHandMiddle1','leftHandMiddle2','leftHandMiddle3',
      'leftHandRing1','leftHandRing2','leftHandRing3',
      'leftHandPinky1','leftHandPinky2','leftHandPinky3',
    ];
    const ALL_POSEABLE_BONES = ARM_BONES.concat(FINGER_BONE_KEYS);
    const _qA = new THREE.Quaternion();
    const _qB = new THREE.Quaternion();
    const _vA = new THREE.Vector3();
    const _vB = new THREE.Vector3();
    const _vC = new THREE.Vector3();
    const _mA = new THREE.Matrix4();

    // ── Messaging ──────────────────────────────────────────────────────────────
    function send(payload) {
      if (window.ReactNativeWebView) {
        window.ReactNativeWebView.postMessage(JSON.stringify(payload));
      }
    }

    // ── Bone discovery ─────────────────────────────────────────────────────────
    // Maps our canonical bone names to possible Mixamo / VRM / custom name fragments
    const BONE_MAP = {
      // Spine / neck
      spine:              ['spine', 'chest', 'mixamorig:spine', 'mixamorig:spine1', 'mixamorig:spine2'],
      neck:               ['neck', 'mixamorig:neck'],
      head:               ['head', 'mixamorig:head'],
      // Right arm
      rightShoulder:      ['rightshoulder', 'r_shoulder', 'mixamorig:rightshoulder'],
      rightArm:           ['rightarm', 'right_arm', 'r_arm', 'rarm', 'mixamorig:rightarm'],
      rightForeArm:       ['rightforearm', 'right_forearm', 'r_forearm', 'mixamorig:rightforearm'],
      rightHand:          ['righthand', 'right_hand', 'r_hand', 'mixamorig:righthand'],
      // Left arm
      leftShoulder:       ['leftshoulder', 'l_shoulder', 'mixamorig:leftshoulder'],
      leftArm:            ['leftarm', 'left_arm', 'l_arm', 'larm', 'mixamorig:leftarm'],
      leftForeArm:        ['leftforearm', 'left_forearm', 'l_forearm', 'mixamorig:leftforearm'],
      leftHand:           ['lefthand', 'left_hand', 'l_hand', 'mixamorig:lefthand'],
      // Right fingers
      rightHandThumb1:    ['righthandthumb1', 'mixamorig:righthandthumb1'],
      rightHandThumb2:    ['righthandthumb2', 'mixamorig:righthandthumb2'],
      rightHandThumb3:    ['righthandthumb3', 'mixamorig:righthandthumb3'],
      rightHandIndex1:    ['righthandindex1', 'righthandindexproximal', 'mixamorig:righthandindex1'],
      rightHandIndex2:    ['righthandindex2', 'righthandindexintermediate', 'mixamorig:righthandindex2'],
      rightHandIndex3:    ['righthandindex3', 'righthandindexdistal', 'mixamorig:righthandindex3'],
      rightHandMiddle1:   ['righthandmiddle1', 'mixamorig:righthandmiddle1'],
      rightHandMiddle2:   ['righthandmiddle2', 'mixamorig:righthandmiddle2'],
      rightHandMiddle3:   ['righthandmiddle3', 'mixamorig:righthandmiddle3'],
      rightHandRing1:     ['righthandring1', 'mixamorig:righthandring1'],
      rightHandRing2:     ['righthandring2', 'mixamorig:righthandring2'],
      rightHandRing3:     ['righthandring3', 'mixamorig:righthandring3'],
      rightHandPinky1:    ['righthandpinky1', 'mixamorig:righthandpinky1'],
      rightHandPinky2:    ['righthandpinky2', 'mixamorig:righthandpinky2'],
      rightHandPinky3:    ['righthandpinky3', 'mixamorig:righthandpinky3'],
      // Left fingers
      leftHandThumb1:     ['lefthandthumb1', 'mixamorig:lefthandthumb1'],
      leftHandThumb2:     ['lefthandthumb2', 'mixamorig:lefthandthumb2'],
      leftHandThumb3:     ['lefthandthumb3', 'mixamorig:lefthandthumb3'],
      leftHandIndex1:     ['lefthandindex1', 'mixamorig:lefthandindex1'],
      leftHandIndex2:     ['lefthandindex2', 'mixamorig:lefthandindex2'],
      leftHandIndex3:     ['lefthandindex3', 'mixamorig:lefthandindex3'],
      leftHandMiddle1:    ['lefthandmiddle1', 'mixamorig:lefthandmiddle1'],
      leftHandMiddle2:    ['lefthandmiddle2', 'mixamorig:lefthandmiddle2'],
      leftHandMiddle3:    ['lefthandmiddle3', 'mixamorig:lefthandmiddle3'],
      leftHandRing1:      ['lefthandring1', 'mixamorig:lefthandring1'],
      leftHandRing2:      ['lefthandring2', 'mixamorig:lefthandring2'],
      leftHandRing3:      ['lefthandring3', 'mixamorig:lefthandring3'],
      leftHandPinky1:     ['lefthandpinky1', 'mixamorig:lefthandpinky1'],
      leftHandPinky2:     ['lefthandpinky2', 'mixamorig:lefthandpinky2'],
      leftHandPinky3:     ['lefthandpinky3', 'mixamorig:lefthandpinky3'],
    };

    function setIdlePlaying(on) {
      if (!idleAction) return;
      if (on) {
        idleAction.reset();
        idleAction.setEffectiveWeight(1);
        idleAction.play();
      } else {
        idleAction.setEffectiveWeight(0);
        idleAction.stop();
      }
    }

    function registerBone(obj) {
      if (!obj || !obj.name) return;
      const cleanName = obj.name.toLowerCase().replace(/[_\\s]/g, '');
      Object.keys(BONE_MAP).forEach(function(key) {
        if (window.bones[key]) return;
        const matched = BONE_MAP[key].some(function(kw) {
          const kwClean = kw.replace(/[_\\s:]/g, '');
          return cleanName === kwClean || cleanName.includes(kwClean);
        });
        if (matched) window.bones[key] = obj;
      });
    }

    function findAvatarBones(root) {
      window.bones = {};
      avatarRoot = root;

      root.traverse(function(obj) {
        if (obj.isBone || obj.type === 'Bone') registerBone(obj);
        if (obj.isSkinnedMesh && obj.skeleton) {
          obj.skeleton.bones.forEach(registerBone);
        }
      });

      restQuats = {};
      restBoneDirs = {};
      restWorldDirs = {};
      root.updateMatrixWorld(true);

      Object.keys(window.bones).forEach(function(k) {
        const bone = window.bones[k];
        restQuats[k] = bone.quaternion.clone();

        _vA.set(0, 0, 0);
        bone.getWorldPosition(_vA);
        if (bone.children && bone.children.length > 0) {
          bone.children[0].getWorldPosition(_vB);
        } else {
          _vB.copy(bone.position).applyQuaternion(bone.quaternion).add(_vA);
        }
        restWorldDirs[k] = _vB.sub(_vA).normalize();

        if (bone.children && bone.children.length > 0) {
          // child.position is in bone-local; rotate by rest quat → parent-local
          restBoneDirs[k] = bone.children[0].position.clone()
            .applyQuaternion(bone.quaternion)
            .normalize();
        } else if (bone.position.lengthSq() > 1e-6) {
          restBoneDirs[k] = bone.position.clone().normalize();
        } else if (k.startsWith('right')) {
          restBoneDirs[k] = new THREE.Vector3(0, -1, 0);
        } else if (k.startsWith('left')) {
          restBoneDirs[k] = new THREE.Vector3(0, -1, 0);
        } else {
          restBoneDirs[k] = new THREE.Vector3(0, 1, 0);
        }
      });

      const boneCount = Object.keys(window.bones).length;
      send({type: 'BONES', count: boneCount, names: Object.keys(window.bones)});
    }

    // ── Bone animation (joint IK + safe fallback) ─────────────────────────────
    function getShoulderBone(side) {
      return window.bones[side + 'Shoulder'] || window.bones[side + 'Arm'];
    }

    function clampQuatDelta(delta, maxRad) {
      const angle = 2 * Math.acos(THREE.MathUtils.clamp(Math.abs(delta.w), 0, 1));
      if (angle <= maxRad) return delta;
      const t = maxRad / angle;
      return delta.clone().slerp(new THREE.Quaternion(), 1 - t);
    }

    function aimBoneAtWorldPoint(boneName, worldPoint, maxRad) {
      const bone = window.bones[boneName];
      if (!bone || !bone.parent) return false;

      const parent = bone.parent;
      parent.updateMatrixWorld(true);
      _mA.copy(parent.matrixWorld).invert();

      bone.getWorldPosition(_vA);
      _vB.copy(worldPoint).applyMatrix4(_mA);
      _vC.copy(_vA).applyMatrix4(_mA);
      _vB.sub(_vC);
      if (_vB.lengthSq() < 1e-6) return false;
      _vB.normalize();

      const restDir = restBoneDirs[boneName];
      if (!restDir) return false;

      const delta = new THREE.Quaternion().setFromUnitVectors(restDir, _vB);
      bone.quaternion.copy(restQuats[boneName]).multiply(clampQuatDelta(delta, maxRad || 2.2));
      return true;
    }

    function jointToWorld(shoulderBone, joint) {
      shoulderBone.getWorldPosition(_vA);
      return _vA.clone().add(
        new THREE.Vector3(joint.x, joint.y, joint.z).multiplyScalar(JOINT_SCALE),
      );
    }

    function applyArmIK(side, joints) {
      const shoulder = getShoulderBone(side);
      const upper = window.bones[side + 'Arm'];
      const fore = window.bones[side + 'ForeArm'];
      if (!shoulder || !upper || !fore || !joints) return;

      const elbowKey = side + 'Elbow';
      const wristKey = side + 'Wrist';
      if (!joints[elbowKey] || !joints[wristKey]) return;

      upper.quaternion.copy(restQuats[side + 'Arm']);
      fore.quaternion.copy(restQuats[side + 'ForeArm']);

      const elbowWorld = jointToWorld(shoulder, joints[elbowKey]);
      const wristWorld = jointToWorld(shoulder, joints[wristKey]);

      aimBoneAtWorldPoint(side + 'Arm', elbowWorld, 2.4);
      avatarRoot.updateMatrixWorld(true);
      aimBoneAtWorldPoint(side + 'ForeArm', wristWorld, 2.4);
    }

    // Root-to-tip order so each parent transform is committed before children use it
    const APPLY_ORDER = [
      'rightArm','rightForeArm','rightHand',
      'leftArm','leftForeArm','leftHand',
      'rightHandThumb1','rightHandThumb2','rightHandThumb3',
      'rightHandIndex1','rightHandIndex2','rightHandIndex3',
      'rightHandMiddle1','rightHandMiddle2','rightHandMiddle3',
      'rightHandRing1','rightHandRing2','rightHandRing3',
      'rightHandPinky1','rightHandPinky2','rightHandPinky3',
      'leftHandThumb1','leftHandThumb2','leftHandThumb3',
      'leftHandIndex1','leftHandIndex2','leftHandIndex3',
      'leftHandMiddle1','leftHandMiddle2','leftHandMiddle3',
      'leftHandRing1','leftHandRing2','leftHandRing3',
      'leftHandPinky1','leftHandPinky2','leftHandPinky3',
    ];

    function getClamp(name) {
      if (/[123]$/.test(name)) return 1.4;       // finger segment
      if (name === 'rightHand' || name === 'leftHand') return 1.5; // wrist
      return 2.2;                                 // upper arm / forearm
    }

    function applyBoneFrame(frameData) {
      if (!frameData || !avatarRoot) return;

      // Reset every poseable bone to rest pose first
      ALL_POSEABLE_BONES.forEach(function(name) {
        if (window.bones[name] && restQuats[name]) {
          window.bones[name].quaternion.copy(restQuats[name]);
        }
      });
      avatarRoot.updateMatrixWorld(true);

      // Apply direction vectors from root to tip — each bone is committed with
      // updateMatrixWorld so the next bone in the chain sees the correct parent transform
      APPLY_ORDER.forEach(function(boneName) {
        if (!frameData[boneName]) return;
        const bone = window.bones[boneName];
        if (!bone || !bone.parent) return;

        const fd = frameData[boneName];
        _vC.set(fd.x, fd.y, fd.z);
        // MediaPipe POSE z-depth is estimated from 2D video — mean |z| is 0.58–0.91
        // across all signs, making it the dominant (and wrong) axis. ZERO IT.
        // Hand landmark z comes from a proper 3D model and IS reliable — keep it.
        if (boneName === 'rightArm' || boneName === 'rightForeArm' ||
            boneName === 'leftArm'  || boneName === 'leftForeArm') {
          _vC.z = 0;
        }
        if (_vC.lengthSq() < 1e-6) return;
        _vC.normalize();

        bone.parent.updateMatrixWorld(true);
        bone.parent.getWorldQuaternion(_qA);
        _qB.copy(_qA).invert();
        _vB.copy(_vC).applyQuaternion(_qB);  // target direction in parent-local space
        _vB.normalize();

        // Correct formula: bone local +Y should point at _vB in parent-local space.
        // setFromUnitVectors((0,1,0), _vB) gives exactly that rotation.
        // Using restQuat * delta was wrong: restQuat * delta @ (0,1,0) != _vB unless
        // restQuat is identity, which it is not — causing the arm to drift behind avatar.
        const delta = new THREE.Quaternion().setFromUnitVectors(
          new THREE.Vector3(0, 1, 0), _vB
        );
        bone.quaternion.copy(clampQuatDelta(delta, getClamp(boneName)));
        bone.updateMatrixWorld(true);
      });

      avatarRoot.updateMatrixWorld(true);
    }

    function returnToIdle() {
      if (idleTimer) clearInterval(idleTimer);
      let t = 0;
      const capturedQuats = {};
      Object.keys(window.bones).forEach(function(k) {
        capturedQuats[k] = window.bones[k].quaternion.clone();
      });
      idleTimer = setInterval(function() {
        t += 0.08;
        if (t >= 1) {
          t = 1;
          clearInterval(idleTimer);
          idleTimer = null;
          setIdlePlaying(true);
        }
        Object.keys(window.bones).forEach(function(k) {
          if (!restQuats[k]) return;
          window.bones[k].quaternion.slerpQuaternions(capturedQuats[k], restQuats[k], t);
        });
        if (avatarRoot) avatarRoot.updateMatrixWorld(true);
      }, 16);
    }

    // ── Public API: called from React Native ───────────────────────────────────
    window.playAnimation = function(frames, fps) {
      if (!frames || !Array.isArray(frames) || !frames.length) {
        send({type: 'ANIM_ERROR', message: 'No animation frames'});
        return;
      }
      if (Object.keys(window.bones).length === 0) {
        send({type: 'ANIM_ERROR', message: 'Avatar bones not mapped yet'});
        return;
      }

      gestureActive = true;
      setIdlePlaying(false);

      if (animTimer) clearInterval(animTimer);
      if (idleTimer) clearInterval(idleTimer);
      if (returnIdleTimeout) { clearTimeout(returnIdleTimeout); returnIdleTimeout = null; }

      animFrames = frames;
      animIndex  = 0;
      animFPS    = fps || 12;

      applyBoneFrame(animFrames[0]);
      send({type: 'ANIM_START', frames: animFrames.length});

      animTimer = setInterval(function() {
        animIndex++;
        if (animIndex >= animFrames.length) {
          clearInterval(animTimer);
          animTimer = null;
          gestureActive = false;
          send({type: 'ANIM_DONE'});
          returnIdleTimeout = setTimeout(returnToIdle, 300);
          return;
        }
        applyBoneFrame(animFrames[animIndex]);
      }, 1000 / animFPS);
    };

    // Legacy single-frame support (from old psl_library.json)
    window.playGesture = function(bonesData) {
      if (!bonesData) return;
      if (Array.isArray(bonesData)) {
        window.playAnimation(bonesData);
      } else {
        // old format: single frame object
        window.playAnimation([bonesData]);
      }
    };

    // ── Scene setup ────────────────────────────────────────────────────────────
    function fitModelToView(model) {
      const box    = new THREE.Box3().setFromObject(model);
      const center = box.getCenter(new THREE.Vector3());
      const size   = box.getSize(new THREE.Vector3());
      const scale  = size.y ? 3 / size.y : 1;
      model.position.set(-center.x, -center.y + 0.5, -center.z);
      model.rotation.set(0, 0, 0);
      model.scale.set(scale, scale, scale);
      fixedAvatarPosition.copy(model.position);
      fixedAvatarScale = scale;
      scene.add(model);
    }

    function lockAvatarRootTransform() {
      if (!avatarRoot) return;
      avatarRoot.position.copy(fixedAvatarPosition);
      avatarRoot.rotation.set(0, 0, 0);
      avatarRoot.scale.set(fixedAvatarScale, fixedAvatarScale, fixedAvatarScale);
      avatarRoot.updateMatrixWorld(true);
    }

    function loadAvatarModel(loader, index) {
      const url = MODEL_URLS[index];
      if (!url) { send({type: 'ERROR', message: 'Unable to load avatar model'}); return; }

      loader.load(
        url,
        function(gltf) {
          document.getElementById('status').style.display = 'none';
          const model = gltf.scene;
          fitModelToView(model);

          if (gltf.animations && gltf.animations.length > 0) {
            mixer = new THREE.AnimationMixer(model);
            idleAction = mixer.clipAction(gltf.animations[0]);
            idleAction.play();
          }

          findAvatarBones(model);
          send({type: 'LOADED'});
        },
        undefined,
        function() { loadAvatarModel(loader, index + 1); }
      );
    }

    function animate() {
      requestAnimationFrame(animate);
      const delta = clock.getDelta();
      if (mixer && !gestureActive) mixer.update(delta);
      lockAvatarRootTransform();
      if (controls) controls.update();
      renderer.render(scene, camera);
    }

    function init() {
      clock    = new THREE.Clock();
      scene    = new THREE.Scene();
      camera   = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 1000);
      camera.position.set(0, 1.5, 5);
      camera.lookAt(0, 1, 0);

      renderer = new THREE.WebGLRenderer({antialias: true, alpha: true, powerPreference: 'high-performance'});
      renderer.setClearColor(0x000000, 0);
      renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 3));
      renderer.outputEncoding = THREE.sRGBEncoding;
      renderer.toneMapping = THREE.ACESFilmicToneMapping;
      renderer.toneMappingExposure = 1.05;
      renderer.setSize(window.innerWidth, window.innerHeight);
      document.body.appendChild(renderer.domElement);

      controls = new THREE.OrbitControls(camera, renderer.domElement);
      controls.enableDamping = true;
      controls.enablePan    = false;
      controls.enableRotate = false;
      controls.enableZoom   = false;
      controls.minDistance  = 2;
      controls.maxDistance  = 10;
      controls.target.set(0, 1, 0);

      const ambient = new THREE.AmbientLight(0xffffff, 0.8);
      scene.add(ambient);
      const keyLight = new THREE.DirectionalLight(0xffffff, 2.2);
      keyLight.position.set(3, 8, 5);
      scene.add(keyLight);
      const fillLight = new THREE.DirectionalLight(0xffffff, 0.6);
      fillLight.position.set(-5, 2, -2);
      scene.add(fillLight);

      loadAvatarModel(new THREE.GLTFLoader(), 0);
      animate();
    }

    window.addEventListener('resize', function() {
      camera.aspect = window.innerWidth / window.innerHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(window.innerWidth, window.innerHeight);
    });

    init();
  </script>
</body>
</html>
`;

// ─── Fuzzy word matcher ────────────────────────────────────────────────────────

function findBestMatch(spoken, library) {
  const normalized = spoken.toLowerCase().trim();
  const keys = Object.keys(library);

  // 1. Exact match
  if (library[normalized]) return normalized;

  // 2. Spoken text contains a library key (handles extra words)
  const containsMatch = keys.find(k => normalized.includes(k));
  if (containsMatch) return containsMatch;

  // 3. Library key contains all words from spoken text
  const words = normalized.split(/\s+/);
  const allWordsMatch = keys.find(k => words.every(w => k.includes(w)));
  if (allWordsMatch) return allWordsMatch;

  // 4. Levenshtein-like: find key with most overlapping words
  let bestKey = null;
  let bestScore = 0;
  keys.forEach(k => {
    const kWords = k.split(/\s+/);
    const overlap = words.filter(w =>
      kWords.some(kw => kw.includes(w) || w.includes(kw)),
    ).length;
    const score = overlap / Math.max(words.length, kWords.length);
    if (score > bestScore) {
      bestScore = score;
      bestKey = k;
    }
  });

  return bestScore > 0.4 ? bestKey : null;
}

// ─── Main Avatar Component ────────────────────────────────────────────────────

export default function Avatar() {
  const isDarkMode = useSelector(state => state.theme?.isDarkMode);
  const webViewRef = useRef(null);
  const pendingAnimRef = useRef(null);

  const [isLoaded, setIsLoaded] = useState(false);
  const [loadError, setLoadError] = useState('');
  const [isRecording, setIsRecording] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [spokenText, setSpokenText] = useState('');
  const [matchedSign, setMatchedSign] = useState('');
  const [noMatch, setNoMatch] = useState(false);
  const [boneCount, setBoneCount] = useState(0);

  const signQueueRef = useRef([]);
  const signQueueIdxRef = useRef(0);

  const pulseAnim = useRef(new Animated.Value(1)).current;
  const pulseLoop = useRef(null);

  const libraryKeys = useMemo(() => Object.keys(pslLibrary), []);

  const injectFrames = frames => {
    if (!webViewRef.current || !frames?.length) return;
    setIsPlaying(true);
    webViewRef.current.injectJavaScript(
      `window.playAnimation(${JSON.stringify(frames)}, 12); true;`,
    );
  };

  const playAnimation = name => {
    const data = pslLibrary[name];
    if (!data) return;
    const frames = Array.isArray(data) ? data : [data];
    if (!isLoaded || boneCount === 0) {
      pendingAnimRef.current = frames;
      return;
    }
    injectFrames(frames);
  };

  const playFromQueue = () => {
    const q = signQueueRef.current;
    const i = signQueueIdxRef.current;
    if (i >= q.length) {
      return;
    }
    signQueueIdxRef.current = i + 1;
    const name = q[i];
    const data = pslLibrary[name];
    if (!data) {
      playFromQueue();
      return;
    }
    injectFrames(Array.isArray(data) ? data : [data]);
  };

  useEffect(() => {
    if (isLoaded && boneCount > 0 && pendingAnimRef.current) {
      injectFrames(pendingAnimRef.current);
      pendingAnimRef.current = null;
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoaded, boneCount]);

  // ── Voice Recognition Setup ────────────────────────────────────────────────
  const handleVoiceResultRef = useRef(null);
  handleVoiceResultRef.current = handleVoiceResult;

  useEffect(() => {
    Voice.onSpeechResults = e => {
      const text = e.value?.[0] || '';
      setSpokenText(text);
      handleVoiceResultRef.current(text);
    };
    Voice.onSpeechError = () => {
      setIsRecording(false);
      stopPulse();
    };
    Voice.onSpeechEnd = () => {
      setIsRecording(false);
      stopPulse();
    };

    requestMicPermission();

    return () => {
      Voice.destroy().then(Voice.removeAllListeners);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const requestMicPermission = async () => {
    if (Platform.OS === 'android') {
      await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
      );
    }
  };

  // ── Mic animation ──────────────────────────────────────────────────────────
  const startPulse = () => {
    pulseLoop.current = Animated.loop(
      Animated.sequence([
        Animated.timing(pulseAnim, {
          toValue: 1.2,
          duration: 500,
          useNativeDriver: true,
        }),
        Animated.timing(pulseAnim, {
          toValue: 1.0,
          duration: 500,
          useNativeDriver: true,
        }),
      ]),
    );
    pulseLoop.current.start();
  };

  const stopPulse = () => {
    pulseLoop.current?.stop();
    Animated.spring(pulseAnim, {toValue: 1, useNativeDriver: true}).start();
  };

  // ── Voice recording ────────────────────────────────────────────────────────
  const startRecording = async () => {
    setSpokenText('');
    setMatchedSign('');
    setNoMatch(false);
    setIsRecording(true);
    startPulse();
    try {
      await Voice.start('en-US');
    } catch (e) {
      console.warn('Voice start error:', e);
      setIsRecording(false);
      stopPulse();
    }
  };

  const stopRecording = async () => {
    setIsRecording(false);
    stopPulse();
    try {
      await Voice.stop();
    } catch (e) {
      console.warn('Voice stop error:', e);
    }
  };

  const handleVoiceResult = text => {
    if (!text) return;

    // Reset queue so previous multi-word sequence doesn't bleed in
    signQueueRef.current = [];
    signQueueIdxRef.current = 0;

    // 1. Try the full spoken phrase first
    const fullMatch = findBestMatch(text, pslLibrary);
    if (fullMatch) {
      setMatchedSign(fullMatch);
      setNoMatch(false);
      playAnimation(fullMatch);
      return;
    }

    // 2. Word-by-word fallback — sign each word sequentially
    const words = text.toLowerCase().trim().split(/\s+/);
    const matched = words
      .map(w => findBestMatch(w, pslLibrary))
      .filter(Boolean);
    if (matched.length > 0) {
      setMatchedSign(matched.join(' → '));
      setNoMatch(false);
      signQueueRef.current = matched;
      signQueueIdxRef.current = 1; // first word played below; rest via queue
      playAnimation(matched[0]);
    } else {
      setNoMatch(true);
    }
  };

  // ── Inject animation into WebView ──────────────────────────────────────────
  // playAnimation is defined above (queues until avatar bones are ready)

  // ── WebView messages ────────────────────────────────────────────────────────
  const handleViewerMessage = event => {
    try {
      const data = JSON.parse(event.nativeEvent.data);
      if (data.type === 'LOADED') {
        setIsLoaded(true);
        setLoadError('');
      }
      if (data.type === 'BONES') {
        setBoneCount(data.count || 0);
      }
      if (data.type === 'ANIM_START') {
        setIsPlaying(true);
      }
      if (data.type === 'ANIM_DONE') {
        setIsPlaying(false);
        playFromQueue();
      }
      if (data.type === 'ANIM_ERROR') {
        setIsPlaying(false);
        setLoadError(data.message || 'Animation failed');
      }
      if (data.type === 'ERROR') {
        setLoadError(data.message || 'Avatar load failed');
      }
    } catch {
      /* ignore */
    }
  };

  const modelUris = useMemo(() => {
    try {
      const asset = Image.resolveAssetSource(
        require('../assets/models/avatar_model.glb'),
      );
      const metro =
        asset?.uri?.replace('localhost', '10.0.2.2') || METRO_FALLBACK_URI;
      return [metro, ANDROID_ASSET_URI];
    } catch {
      return [METRO_FALLBACK_URI, ANDROID_ASSET_URI];
    }
  }, []);

  const viewerHtml = useMemo(() => createViewerHtml(modelUris), [modelUris]);
  const C = useMemo(() => colors(isDarkMode), [isDarkMode]);

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <View style={[ss.screen, {backgroundColor: C.bg}]}>
      <ScrollView
        style={ss.scroll}
        contentContainerStyle={ss.content}
        showsVerticalScrollIndicator={false}>
        {/* ── Header ── */}
        <View style={ss.header}>
          <View style={ss.headerCopy}>
            <Text style={[ss.title, {color: C.text}]}>PSL Avatar</Text>
            <Text style={[ss.subtitle, {color: C.sub}]}>
              Speak a word — watch it signed in 3D
            </Text>
          </View>
          <Image
            source={AvatarImg}
            style={[ss.headerThumb, {borderColor: C.primary}]}
          />
        </View>

        {/* ── 3D Viewer ── */}
        <RNAnimatable.View
          animation="fadeIn"
          duration={800}
          style={ss.viewerWrap}>
          <WebView
            ref={webViewRef}
            originWhitelist={['*']}
            source={{html: viewerHtml, baseUrl: 'http://10.0.2.2:8081'}}
            style={ss.webView}
            scrollEnabled={false}
            javaScriptEnabled
            mixedContentMode="always"
            allowFileAccess
            allowUniversalAccessFromFileURLs
            domStorageEnabled
            androidLayerType="hardware"
            renderToHardwareTextureAndroid
            onMessage={handleViewerMessage}
          />

          {/* Overlay status badges */}
          <View style={ss.badgeRow}>
            <View
              style={[
                ss.badge,
                {backgroundColor: isLoaded ? '#10B981' : '#F59E0B'},
              ]}>
              <Text style={ss.badgeTxt}>
                {isLoaded ? '● LIVE' : '⏳ Loading'}
              </Text>
            </View>
            {boneCount > 0 && (
              <View style={[ss.badge, {backgroundColor: '#6366F1'}]}>
                <Text style={ss.badgeTxt}>{boneCount} bones</Text>
              </View>
            )}
            {isPlaying && (
              <View style={[ss.badge, {backgroundColor: '#EC4899'}]}>
                <Text style={ss.badgeTxt}>▶ Signing…</Text>
              </View>
            )}
          </View>
        </RNAnimatable.View>

        {loadError ? (
          <Text style={[ss.errorTxt, {color: '#EF4444'}]}>{loadError}</Text>
        ) : null}

        {/* ── Voice Input ── */}
        <RNAnimatable.View
          animation="fadeInUp"
          delay={300}
          style={[ss.voiceCard, {backgroundColor: C.card}]}>
          <Text style={[ss.cardTitle, {color: C.text}]}>🎙 Voice to Sign</Text>
          <Text style={[ss.cardSub, {color: C.sub}]}>
            Press and speak any word from the library
          </Text>

          {/* Mic button */}
          <Animated.View
            style={{
              transform: [{scale: pulseAnim}],
              alignSelf: 'center',
              marginTop: 20,
            }}>
            <Pressable
              onPress={isRecording ? stopRecording : startRecording}
              style={[ss.micBtn, isRecording && {backgroundColor: '#EF4444'}]}>
              <FontAwesome5
                name={isRecording ? 'stop' : 'microphone'}
                size={32}
                color="#fff"
              />
            </Pressable>
          </Animated.View>
          <Text style={[ss.micLabel, {color: C.sub}]}>
            {isRecording ? 'Listening… tap to stop' : 'Tap to speak'}
          </Text>

          {/* Result row */}
          {spokenText ? (
            <View style={[ss.resultRow, {borderColor: C.primary + '40'}]}>
              <View style={ss.resultItem}>
                <Text style={[ss.resultLabel, {color: C.sub}]}>Heard</Text>
                <Text style={[ss.resultValue, {color: C.text}]}>
                  {spokenText}
                </Text>
              </View>
              {matchedSign ? (
                <View style={ss.resultItem}>
                  <Text style={[ss.resultLabel, {color: C.sub}]}>Signing</Text>
                  <Text style={[ss.resultValue, {color: C.primary}]}>
                    {matchedSign}
                  </Text>
                </View>
              ) : noMatch ? (
                <View style={ss.resultItem}>
                  <Text style={[ss.resultLabel, {color: '#EF4444'}]}>
                    No sign found
                  </Text>
                  <Text style={[ss.resultValue, {color: C.sub}]}>
                    Try a listed word
                  </Text>
                </View>
              ) : null}
            </View>
          ) : null}
        </RNAnimatable.View>

        {/* ── Sign Library ── */}
        <View style={ss.libHeader}>
          <Text style={[ss.libTitle, {color: C.text}]}>Sign Library</Text>
          <View style={[ss.countBadge, {backgroundColor: C.primary}]}>
            <Text style={ss.countTxt}>{libraryKeys.length} SIGNS</Text>
          </View>
        </View>

        {libraryKeys.length === 0 ? (
          <Text style={[ss.emptyTxt, {color: C.sub}]}>
            Run backend/extract_holistic_animation.py to generate animations
          </Text>
        ) : (
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            style={ss.libScroll}>
            {libraryKeys.map(name => (
              <Pressable
                key={name}
                onPress={() => {
                  setMatchedSign(name);
                  setSpokenText('');
                  setNoMatch(false);
                  playAnimation(name);
                }}
                style={({pressed}) => [
                  ss.signBtn,
                  {backgroundColor: C.card},
                  pressed && ss.pressed,
                  matchedSign === name && {
                    borderColor: C.primary,
                    borderWidth: 2,
                  },
                ]}>
                <View
                  style={[ss.signIcon, {backgroundColor: C.primary + '20'}]}>
                  <FontAwesome5
                    name="sign-language"
                    size={20}
                    color={C.primary}
                  />
                </View>
                <Text style={[ss.signLabel, {color: C.text}]}>
                  {name.charAt(0).toUpperCase() + name.slice(1)}
                </Text>
              </Pressable>
            ))}
          </ScrollView>
        )}

        <RNAnimatable.View
          animation="fadeInUp"
          delay={600}
          style={[
            ss.infoCard,
            {backgroundColor: C.primary + '12', borderColor: C.primary + '25'},
          ]}>
          <FontAwesome5
            name="info-circle"
            size={16}
            color={C.primary}
            style={{marginBottom: 8}}
          />
          <Text style={[ss.infoTxt, {color: C.text}]}>
            Animations are extracted directly from real PSL videos using
            MediaPipe pose & hand tracking — no guesswork, just accurate bone
            data.
          </Text>
        </RNAnimatable.View>
      </ScrollView>
    </View>
  );
}

// ─── Design tokens ──────────────────────────────────────────────────────────

const colors = dark => ({
  bg: dark ? '#0B1120' : '#F1F5F9',
  card: dark ? '#1A2236' : '#FFFFFF',
  text: dark ? '#F1F5F9' : '#0F172A',
  sub: dark ? '#94A3B8' : '#64748B',
  primary: '#6366F1',
});

// ─── Styles ─────────────────────────────────────────────────────────────────

const ss = StyleSheet.create({
  screen: {flex: 1},
  scroll: {paddingHorizontal: 20},
  content: {paddingBottom: 120},

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 60,
  },
  headerCopy: {flex: 1},
  title: {fontSize: 28, fontWeight: '800', letterSpacing: -0.5},
  subtitle: {fontSize: 13, marginTop: 4, lineHeight: 18},
  headerThumb: {width: 48, height: 48, borderRadius: 24, borderWidth: 2},

  viewerWrap: {
    marginTop: 20,
    height: 420,
    borderRadius: 28,
    overflow: 'hidden',
    position: 'relative',
  },
  webView: {width: AVATAR_SIZE, height: 420, backgroundColor: 'transparent'},
  badgeRow: {
    position: 'absolute',
    top: 12,
    left: 12,
    flexDirection: 'row',
    gap: 6,
  },
  badge: {paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20},
  badgeTxt: {color: '#fff', fontSize: 10, fontWeight: '700'},

  errorTxt: {textAlign: 'center', marginTop: 8, fontSize: 12},

  voiceCard: {borderRadius: 24, padding: 22, marginTop: 24},
  cardTitle: {fontSize: 18, fontWeight: '800'},
  cardSub: {fontSize: 12, marginTop: 4},
  micBtn: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#6366F1',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 12,
  },
  micLabel: {textAlign: 'center', marginTop: 10, fontSize: 12},
  resultRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
  },
  resultItem: {flex: 1},
  resultLabel: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  resultValue: {fontSize: 16, fontWeight: '700', marginTop: 2},

  libHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 28,
    marginBottom: 14,
  },
  libTitle: {fontSize: 18, fontWeight: '800'},
  countBadge: {paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12},
  countTxt: {color: '#fff', fontSize: 10, fontWeight: '800'},
  libScroll: {marginBottom: 4},
  emptyTxt: {fontSize: 13, textAlign: 'center', marginVertical: 20},

  signBtn: {
    width: 120,
    height: 110,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  signIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  signLabel: {fontSize: 12, fontWeight: '700', textAlign: 'center'},
  pressed: {opacity: 0.8, transform: [{scale: 0.95}]},

  infoCard: {
    borderRadius: 20,
    padding: 20,
    marginTop: 24,
    borderWidth: 1,
    alignItems: 'center',
  },
  infoTxt: {fontSize: 13, lineHeight: 20, textAlign: 'center'},
});
